namespace IRCd.Shared.Options
{
    public sealed class ListenOptions
    {
        public int ClientPort { get; set; } = 6667;

        public int TlsClientPort { get; set; } = 6697;

        public bool EnableTls { get; set; } = false;

        public string? TlsCertificatePath { get; set; }

        public string? TlsCertificatePassword { get; set; }

        public bool AutoGenerateSelfSignedCertificate { get; set; } = false;

        public string AutoGeneratedCertPath { get; set; } = "certs/ircd.pfx";

        public string AutoGeneratedCertPassword { get; set; } = "changeit";

        public int AutoGeneratedCertDaysValid { get; set; } = 30;

        public string AutoGeneratedCertCommonName { get; set; } = "localhost";

        public int ServerPort { get; set; } = 6900;

        public string BindIp { get; set; } = "0.0.0.0";
    }
}
